name: Kernel Build 4.19

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout kernel source
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y bc bison build-essential ccache curl flex git \
            libncurses-dev libssl-dev lld llvm make python3 unzip wget xz-utils zip

      # Cache ccache
      - name: Cache ccache
        uses: actions/cache@v4
        with:
          path: ~/.ccache
          key: ${{ runner.os }}-ccache-${{ github.ref_name }}
          restore-keys: |
            ${{ runner.os }}-ccache-

      # Download GCC 4.9
      - name: Download GCC 4.9
        run: |
          git clone --depth=1 https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9 -b android11-release gcc-4.9

      # Download Clang (Android 10/11 prebuilt)
      - name: Download Clang
        run: |
          wget https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/android10-dev/clang-r353983c.tar.gz -O clang.tar.gz
          mkdir clang && tar -xf clang.tar.gz -C clang

      # Clone Realme C21 Vendor Source parallel to kernel repo
      - name: Clone Realme C21 Vendor Source
        run: |
          cd $GITHUB_WORKSPACE
          git clone --depth=1 https://github.com/realme-kernel-opensource/realme_C21-AndroidR-vendor-source.git ../../realme_C21-AndroidR-vendor-source

      # Set up toolchain PATH
      - name: Setup Toolchain PATH
        run: |
          echo "$GITHUB_WORKSPACE/clang/bin:$GITHUB_WORKSPACE/gcc-4.9/bin:/usr/bin:/bin" >> $GITHUB_PATH

      # Set up ccache
      - name: Set up ccache
        run: |
          mkdir -p ~/.ccache/bin
          ln -sf $(which ccache) ~/.ccache/bin/clang
          ln -sf $(which ccache) ~/.ccache/bin/clang++
          ln -sf $(which ccache) ~/.ccache/bin/aarch64-linux-android-gcc
          ln -sf $(which ccache) ~/.ccache/bin/aarch64-linux-android-g++
          echo "$HOME/.ccache/bin:$PATH" >> $GITHUB_PATH

      # Build kernel
      - name: Build Kernel
        run: |
          export KBUILD_BUILD_USER="snowluna"
          export KBUILD_BUILD_HOST="android-build"
          
          mkdir -p out
          make O=out ARCH=arm64 oppo6765_defconfig
          make -j$(nproc --all) \
            ARCH=arm64 \
            O=out \
            CC=clang \
            CROSS_COMPILE="$GITHUB_WORKSPACE/gcc-4.9/bin/aarch64-linux-android-" \
            CLANG_TRIPLE=aarch64-linux-gnu-

      # Show ccache stats
      - name: Show ccache stats
        run: ccache -s || true

      # Prepare flashable files for artifact
      - name: Prepare flashable files for artifact
        run: |
          mkdir -p artifact
          cp out/arch/arm64/boot/Image.gz-dtb artifact/
          git clone https://github.com/NyxNoirXD/AnyKernel3.git ak
          cp -r ak/* artifact/
          KVER=$(awk '/^VERSION =/ {v=$3} /^PATCHLEVEL =/ {p=$3} /^SUBLEVEL =/ {s=$3} END {print v"."p"."s}' Makefile)
          echo "KVER=$KVER" >> $GITHUB_ENV
          echo "Kernel version: $KVER"

      # Upload artifact
      - name: Upload flashable artifact
        uses: actions/upload-artifact@v4
        with:
          name: lunacore-${{ env.KVER }}
          path: artifact/*
